kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ken-rolebinding
  namespace: ken
subjects:
- kind: User
  name: ken
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ken-role
  apiGroup: rbac.authorization.k8s.io
