kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ken-role
  namespace: ken
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: [pods]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
